server:
  port : ${PORT:80}

spring:
  datasource:
    driver-class-name: ${DRIVER_DB:com.mysql.cj.jdbc.Driver}
    username: ${USER_DB:root}
    password: ${PASSWORD_DB:person}
    url: ${URL_DB:jdbc:mysql://localhost:3306/persondb?useSSL=false}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      jakarta.persistence.query.timeout: 10000